version: '3.8'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=alura_loja
    ports:
      - '5432:5432'
    networks:
      - postgres
    volumes: 
      - db:/Users/evellyn/go/src/loja/database
      - ./init-database.sh:/docker-entrypoint-initdb.d/db_init.sh
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    networks:
      - postgres
networks:
  postgres:
    driver: bridge
volumes:
  db:
    driver: local